- name: Create build directory
  file:
    path: /tmp/RedHat
    state: directory
    mode: '0755'
- name: Copy war file
  copy:
    src: sample.war
    dest: /tmp/RedHat/sample.war
    mode: '0644'
- name: Copy Dockerfile
  copy:
    src: Dockerfile
    dest: /tmp/RedHat/Dockerfile
    mode: '0644'
- name: Build container image
  docker_image:
    name: "{{ container_name }}:{{ tag }}"
    build:
      path: /tmp/RedHat
    source: build
    state: present
